<?php

/**
 * @file
 * Module file for the Site API Key.
 */
 
/**
 * Implements hook_menu().
 */
function page_json_menu() {
  $items = array();
  $items['page_json/%/%'] = array(
  'title' => 'JSON Output of Node',
  'page callback' => 'page_node_json_output',
  'access callback' => TRUE,
  'page arguments' => array(1, 2),
  );
  
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function page_json_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  $form['site_api'] = array(
    '#type' => 'fieldset',
    '#title' => t('Site API Settings'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  // Site API Key
  $form['site_api']['siteapikey'] = array(
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#default_value' => variable_get('siteapikey', 'No API Key yet'),
    '#description' => t('Enter your site API key here.'),
    '#required' => FALSE,
    '#attributes' => array(
      'placeholder' => t('No API Key yet')
    ),
  );

  // Change button name if API Key already set.
  if (variable_get('siteapikey') != NULL) {
    $form['actions']['submit']['#value'] = t('Update Configuration');
  }

  // Include custom form submit.
  $form['#submit'][] = 'custom_siteapikey_settings_form_submit';

  return system_settings_form($form);
}

/**
 * Custom form submit for siteapikey settings.
 */
function custom_siteapikey_settings_form_submit(&$form, &$form_state) {
  if (!empty( $form_state['values']['siteapikey'] )) {
    variable_set('siteapikey', $form_state['values']['siteapikey']);
    drupal_set_message(t('The site API key has been saved with %value', array('%value' => variable_get('siteapikey'))));
  }
}

/**
 * Page callback function to get JSON output.
 */
function page_node_json_output($siteapikey, $nid) {
  if (is_numeric($nid)) {
    $node = node_load($nid);
    if($node->type == 'page' && $siteapikey == variable_get('siteapikey')) {
      drupal_json_output($node);
    }
  }
  drupal_access_denied();  
}
